# Binaries
brew 'awscli'
brew 'bash' # Latest Bash version
brew 'bat' # Used for spatie/visit
brew 'bc'
brew 'coreutils' # Those that come with macOS are outdated
brew 'cosign'
brew 'dockutil'
brew 'emacs'
brew 'ffmpeg'
brew 'gh'
brew 'git'
brew 'grep'
brew 'htop'
brew 'httpie'
brew 'jq'
brew 'mackup'
#brew 'mas' # Mac App Store manager
brew 'ncdu'
brew 'nmap'
brew 'pipx'
brew 'pkg-config' # https://github.com/driesvints/dotfiles/issues/20
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'r'
brew 'rclone'
brew 'starship'
brew 'svn' # Needed to install fonts
brew 'sha2'
brew 'tmux'
brew 'watch'
brew 'wget'

brew 'jpegoptim'
brew 'optipng'
brew 'pngquant'
brew 'svgo'
brew 'gifsicle'

brew 'imagemagick'

# Apps
cask 'adobe-acrobat-reader'
cask 'basictex'
#cask 'alt-tab'
#cask 'dbngin'
cask 'google-chrome@beta'
cask 'google-drive'
#cask 'helo'
cask 'font-fira-code-nerd-font'
cask 'imageoptim'
cask 'insomnia'
cask 'iterm2'
cask 'lulu'
cask 'microsoft-office'
cask 'windows-app'
cask 'microsoft-teams'
#cask 'pastebot'
#cask 'phpmon'
#cask 'ray'
#cask 'raycast'
#cask 'readdle-spark'
#cask 'screenflow'
#cask 'slack'
#cask 'tableplus'
cask 'rectangle'
cask 'rstudio'
cask 'stats'
cask 'the-unarchiver'
#cask 'tinkerwell'
#cask 'transmit'
cask 'tailscale'
#cask 'tuple'
cask 'visual-studio-code@insiders'
cask 'wireshark'
cask 'vlc'
cask 'zoom'
cask 'zotero'

# Quicklook
cask 'qlmarkdown'
cask 'quicklook-json'

# Fonts
cask 'font-lato' 
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-source-code-pro-for-powerline'
cask 'font-source-code-pro'
cask 'font-source-sans-3'
cask 'font-source-serif-4'
cask 'font-fira-code-nerd-font'

